(module
    (func $test1
        (local f64 i32)
        (i32.const 5)
        (f64.const 3.2)
        (i32.const 12)
        (struct.new $test_struct)
        (struct.get $test_struct 0)
        (drop)
        (i32.const 5)
                (f64.const 3.2)
                (i32.const 12)
                (struct.new $test_struct)
                (struct.get $test_struct 0)
                (drop)
    )
    (func $test2
            (local f64 i32)
            (i32.const 5)
            (f64.const 3.2)
            (i32.const 12)
            (struct.new $test_struct)
            (struct.get $test_struct 0)
            (drop)
        )
    (type $test_struct (struct (field i32 f64 i32)))
)
